import { AvailableCategory, UIBudgetCategory } from './types';

// Mock initial categories (used when no API data is available)
export const INITIAL_CATEGORIES: UIBudgetCategory[] = [
  {
    id: '1',
    categoryId: 1,
    name: 'Food & Dining',
    icon: 'restaurant-outline',
    spent: 8200,
    budget: 10000,
    color: '#22c55e',
    iconBgColor: 'bg-emerald-100 dark:bg-emerald-500/20',
  },
  {
    id: '2',
    categoryId: 2,
    name: 'Transportation',
    icon: 'car-outline',
    spent: 4800,
    budget: 5000,
    color: '#f59e0b',
    iconBgColor: 'bg-amber-100 dark:bg-amber-500/20',
  },
  {
    id: '3',
    categoryId: 3,
    name: 'Shopping',
    icon: 'bag-outline',
    spent: 7500,
    budget: 6000,
    color: '#ef4444',
    iconBgColor: 'bg-red-100 dark:bg-red-500/20',
  },
  {
    id: '4',
    categoryId: 4,
    name: 'Entertainment',
    icon: 'game-controller-outline',
    spent: 2400,
    budget: 4000,
    color: '#8b5cf6',
    iconBgColor: 'bg-violet-100 dark:bg-violet-500/20',
  },
  {
    id: '5',
    categoryId: 5,
    name: 'Bills & Utilities',
    icon: 'receipt-outline',
    spent: 3850,
    budget: 8000,
    color: '#3b82f6',
    iconBgColor: 'bg-blue-100 dark:bg-blue-500/20',
  },
  {
    id: '6',
    categoryId: 6,
    name: 'Healthcare',
    icon: 'medkit-outline',
    spent: 1200,
    budget: 3000,
    color: '#ec4899',
    iconBgColor: 'bg-pink-100 dark:bg-pink-500/20',
  },
  {
    id: '7',
    categoryId: 7,
    name: 'Education',
    icon: 'school-outline',
    spent: 800,
    budget: 5000,
    color: '#06b6d4',
    iconBgColor: 'bg-cyan-100 dark:bg-cyan-500/20',
  },
  {
    id: '8',
    categoryId: 8,
    name: 'Personal Care',
    icon: 'sparkles-outline',
    spent: 0,
    budget: 4000,
    color: '#a855f7',
    iconBgColor: 'bg-purple-100 dark:bg-purple-500/20',
  },
];

// Available categories for adding new budgets
export const AVAILABLE_CATEGORIES: AvailableCategory[] = [
  { name: 'Food & Dining', icon: 'restaurant-outline', color: '#22c55e', iconBgColor: 'bg-emerald-100 dark:bg-emerald-500/20', categoryId: 1 },
  { name: 'Transportation', icon: 'car-outline', color: '#f59e0b', iconBgColor: 'bg-amber-100 dark:bg-amber-500/20', categoryId: 2 },
  { name: 'Shopping', icon: 'bag-outline', color: '#ef4444', iconBgColor: 'bg-red-100 dark:bg-red-500/20', categoryId: 3 },
  { name: 'Entertainment', icon: 'game-controller-outline', color: '#8b5cf6', iconBgColor: 'bg-violet-100 dark:bg-violet-500/20', categoryId: 4 },
  { name: 'Bills & Utilities', icon: 'receipt-outline', color: '#3b82f6', iconBgColor: 'bg-blue-100 dark:bg-blue-500/20', categoryId: 5 },
  { name: 'Healthcare', icon: 'medkit-outline', color: '#ec4899', iconBgColor: 'bg-pink-100 dark:bg-pink-500/20', categoryId: 6 },
  { name: 'Education', icon: 'school-outline', color: '#06b6d4', iconBgColor: 'bg-cyan-100 dark:bg-cyan-500/20', categoryId: 7 },
  { name: 'Personal Care', icon: 'sparkles-outline', color: '#a855f7', iconBgColor: 'bg-purple-100 dark:bg-purple-500/20', categoryId: 8 },
  { name: 'Groceries', icon: 'cart-outline', color: '#10b981', iconBgColor: 'bg-green-100 dark:bg-green-500/20', categoryId: 9 },
  { name: 'Subscriptions', icon: 'card-outline', color: '#6366f1', iconBgColor: 'bg-indigo-100 dark:bg-indigo-500/20', categoryId: 10 },
  { name: 'Travel', icon: 'airplane-outline', color: '#0ea5e9', iconBgColor: 'bg-sky-100 dark:bg-sky-500/20', categoryId: 11 },
  { name: 'Gifts', icon: 'gift-outline', color: '#f43f5e', iconBgColor: 'bg-rose-100 dark:bg-rose-500/20', categoryId: 12 },
  { name: 'Savings', icon: 'wallet-outline', color: '#14b8a6', iconBgColor: 'bg-teal-100 dark:bg-teal-500/20', categoryId: 13 },
  { name: 'Other', icon: 'ellipsis-horizontal-outline', color: '#6b7280', iconBgColor: 'bg-gray-100 dark:bg-gray-500/20', categoryId: 14 },
];

// Quick amount options for budget input
export const QUICK_AMOUNT_OPTIONS = [1000, 2500, 5000, 10000, 15000, 20000];
